# Generated by Django 4.1.3 on 2022-11-25 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=15)),
                ('image', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('category', models.CharField(max_length=5)),
                ('link', models.CharField(max_length=500)),
                ('shopName', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=2, max_digits=14)),
                ('lng', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
    ]
