# Generated by Django 4.1.3 on 2022-11-25 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='lat',
            field=models.DecimalField(decimal_places=14, max_digits=18),
        ),
        migrations.AlterField(
            model_name='goods',
            name='lng',
            field=models.DecimalField(decimal_places=14, max_digits=18),
        ),
    ]
