# Generated by Django 4.1.3 on 2022-11-26 00:52
# -*-  -*-
import json
from django.db import migrations


def combine_names(apps, schema_editor):
    # We can't import the Person model directly as it may be a newer
    # version than this migration expects. We use the historical version.
    Goods = apps.get_model('goods', 'Goods')
    with open('D:/django/hackathon/goods/migrations/run_results.json', 'r', encoding='utf-8') as fh:
        data = json.load(fh)
    jsondata = list(data.values())[0]
    for i in jsondata:
        Goods.objects.create(
            name=i['name'],
            description=i['description'],
            price=i['price'],
            image=i['image'],
            rating=1,
            category=i['category'],
            link=i['link'],
            shopName=i['shop'],
            lat=0,
            lng=0
        )


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(combine_names)
    ]


# Generated by Django 4.1.3 on 2022-11-25 23:48
