# Generated by Django 4.1.3 on 2023-01-05 02:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_goods_lat_alter_goods_lng'),
        ('goods', '0002_auto_20221126_0859'),
        ('goods', '0002_auto_20221126_1410'),
    ]

    operations = [
    ]
