# Generated by Django 4.1.3 on 2023-01-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_merge_20230105_0857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='lat',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=18),
        ),
        migrations.AlterField(
            model_name='goods',
            name='lng',
            field=models.DecimalField(decimal_places=14, default=0, max_digits=18),
        ),
    ]
